---
name: CI

env:
  CI: true
  CARGO_TERM_COLOR: always

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    name: Build And Test
    steps:
      - name: Checkout codes
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          target: wasm32-unknown-unknown,wasm32-wasi

      - uses: Swatinem/rust-cache@v2

      - name: Format
        run: cargo fmt --all --check

      - name: Install cargo leptos
        uses: taiki-e/install-action@v2
        with:
            tool: cargo-leptos

      - name: Setup `spin`
        uses: fermyon/actions/spin/setup@v1

      - name: Build
        run: spin build

      - name: Test
        run: cargo test
