---
name: CI

env:
  CI: true
  CARGO_TERM_COLOR: always

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    name: Build And Test
    steps:
      - name: Checkout codes
        uses: actions/checkout@v4

      - name: Setup `spin`
        uses: fermyon/actions/spin/setup@v1

      - name: Run `spin version`
        run: "spin --version"

      - name: Format
        run: cargo fmt --all --check

      - name: Install cargo leptos
        run: cargo install --locked cargo-leptos

      - name: Build
        run: spin build

      - name: Test
        run: cargo test --verbose
